### ISSUE TITLE
Decide on NotNull Annotation codestyle

### ISSUE THREAD

**Issue by Sxtanna** [Project-Coalesce/Core#1]
```java
public @NotNull Type getType()
```

or 

```java
@NotNull
public Type getType()
```

**Comment by TheStilbruch** [comment]
No inline. Inline is uggggggly

**Comment by camdenorrb** [comment]
I'm usually all for inline, but 2nd one looks better for annotations.

**Comment by Sxtanna** [comment]
Also I should clarify, this rule will apply to members that already have annotations as well.

``` java
@Override
public @Notnull Type getType()
```

vs

``` java
@NotNull
@Override
public Type getType()
```

**Comment by NJDaeger** [comment]
I like the second one

**Comment by Lyxnx** [comment]
the latter

**Comment by Sxtanna** [comment]
## Final decision is to follow Google's java codestyle

[Google's Annotation CodeStyle](https://google.github.io/styleguide/javaguide.html#s4.8.5-annotations)
